kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cfs-csi-node
  namespace: chubaofs
spec:
  selector:
    matchLabels:
      app: cfs-csi-node
  template:
    metadata:
      labels:
        app: cfs-csi-node
    spec:
      serviceAccount: cfs-csi-service-account
      nodeSelector:
        jdos.jd.com/zone=default_g.n1jd.15xlarge_m
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: driver-registrar
          image: ishc.harbor.svc.hcyf.n.jd.local/chubaofs35/driver-registrar:v0.4.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --kubeconfig=/etc/kubernetes/config
          env:
            - name: ADDRESS
              value: /export/kubelet/plugins/csi.chubaofs.com/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /export/kubelet/plugins/csi.chubaofs.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /export/kubelet/plugins/csi.chubaofs.com
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
            - name: kube-config
              mountPath: /etc/kubernetes
        - name: cfs-driver
          image: ishc.harbor.svc.hcyf.n.jd.local/chubaofs35/cfs-csi-driver:2.0.9
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /bin/tini
            - "--"
            - bash
            - "-c"
            - |-
              set -e
              su -p -s /bin/bash -c "/cfs/bin/start.sh &"
              su -p -s /bin/bash -c "sleep 9999999d"
          env:
            - name: KUBE_CONFIG
              value: /etc/kubernetes/config
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///export/kubelet/plugins/csi.chubaofs.com/csi.sock
            - name: DRIVER_NAME
              value: csi.chubaofs.com
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /export/kubelet/plugins/csi.chubaofs.com
              name: socket-dir
            - mountPath: /export/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - name: kube-config
              mountPath: /etc/kubernetes
      volumes:
        - hostPath:
            path: /export/kubelet/plugins/csi.chubaofs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /export/kubelet/plugins/
            type: Directory
          name: registration-dir
        - hostPath:
            path: /export/kubelet/pods
            type: Directory
          name: mountpoint-dir
        - configMap:
            name: csi-kube-config
          name: kube-config
